game/urls.py
from django.urls import path

from . import session_views, views

app_name = "game"

urlpatterns = [
    path("list/", views.game_list, name="list"),
    path("my-games/", views.my_games, name="my_games"),
    path("detail/<int:game_pk>/", views.game_detail, name="detail"),
    path("create/", views.create_game, name="new"),
    path("edit/<int:game_pk>/", views.edit_game, name="edit"),
    path("dashboard/<int:game_pk>/", views.game_dashboard, name="dashboard"),
    path("publish/<int:game_pk>/", views.publish_game, name="publish"),
    path("unpublish/<int:game_pk>/", views.unpublish_game, name="unpublish"),
    path("new/end_state/<int:game_pk>/", views.new_end_state, name="new_end_state"),
    path(
        "edit/end_state/<int:end_state_pk>", views.edit_end_state, name="edit_end_state"
    ),
    path(
        "delete/end_state/<int:end_state_pk>",
        views.delete_end_state,
        name="delete_end_state",
    ),
    # session urls
    path(
        "session/start/<int:game_pk>/",
        session_views.start_session,
        name="start_session",
    ),
    path(
        "session/new/<int:game_pk>/",
        session_views.start_new_session,
        name="new_session",
    ),
    path("session/play/<int:session_pk>/", session_views.play_game, name="play"),
    path(
        "session/move/<int:session_pk>/<int:room_pk>/",
        session_views.move_room,
        name="move",
    ),
    path(
        "session/take/<int:session_pk>/<int:item_pk>/",
        session_views.take_item,
        name="take",
    ),
    path(
        "session/open/<int:session_pk>/<int:item_pk>/",
        session_views.open_item,
        name="open",
    ),
]

tbac/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

from . import views

urlpatterns = [
    path("", lambda r: HttpResponseRedirect(reverse("game:list"))),
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("game/", include("game.urls")),
    path("room/", include("room.urls")),
    path("item/", include("item.urls")),
]

templates/base.html


<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}T-BAC{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">T-BAC</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link active" aria-current="page" href="{% url 'game:list' %}">Home</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'game:my_games' %}">My Games</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="container text-center mb-3 mt-2">
        <h2>{% block page_title %}{%endblock %}</h2>
        {% if links %}
          <table class="table" style="table-layout:fixed">
            <tr>
              {% for link_item in links %}
                <th><a style="{{link_item.2}}" href="{{link_item.1}}">{{ link_item.0 }}</a></th>
              {% endfor %}
            </tr>
          </table>
        {% endif %}
      </div>
      {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>

  <script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl)
    })
  </script>
</html>