game/urls.py
from django.urls import path

from . import session_views, views

app_name = "game"

urlpatterns = [
    path("list/", views.game_list, name="list"),
    path("my-games/", views.my_games, name="my_games"),
    path("detail/<int:game_pk>/", views.game_detail, name="detail"),
    path("create/", views.create_game, name="new"),
    path("edit/<int:game_pk>/", views.edit_game, name="edit"),
    path("dashboard/<int:game_pk>/", views.game_dashboard, name="dashboard"),
    path("publish/<int:game_pk>/", views.publish_game, name="publish"),
    path("unpublish/<int:game_pk>/", views.unpublish_game, name="unpublish"),
    path("new/end_state/<int:game_pk>/", views.new_end_state, name="new_end_state"),
    path(
        "edit/end_state/<int:end_state_pk>", views.edit_end_state, name="edit_end_state"
    ),
    path(
        "delete/end_state/<int:end_state_pk>",
        views.delete_end_state,
        name="delete_end_state",
    ),
    # session urls
    path(
        "session/start/<int:game_pk>/",
        session_views.start_session,
        name="start_session",
    ),
    path(
        "session/new/<int:game_pk>/",
        session_views.start_new_session,
        name="new_session",
    ),
    path("session/play/<int:session_pk>/", session_views.play_game, name="play"),
    path(
        "session/move/<int:session_pk>/<int:room_pk>/",
        session_views.move_room,
        name="move",
    ),
    path(
        "session/take/<int:session_pk>/<int:item_pk>/",
        session_views.take_item,
        name="take",
    ),
    path(
        "session/open/<int:session_pk>/<int:item_pk>/",
        session_views.open_item,
        name="open",
    ),
]

item/urls.py
from django.urls import path

from . import views

app_name = "item"

urlpatterns = [
    path("new/<int:game_pk>/", views.create_item, name="new"),
    path("edit/<int:item_pk>/", views.edit_item, name="edit"),
    path("delete/<int:item_pk>/", views.delete_item, name="delete"),
]

room/urls.py
from django.urls import path

from . import views

app_name = "room"

urlpatterns = [
    path("new/<int:game_pk>/", views.create_room, name="new"),
    path("edit/<int:room_pk>/", views.edit_room, name="edit"),
    path(
        "set_starting/<int:room_pk>/", views.set_as_starting_room, name="set_starting"
    ),
    path("delete/<int:room_pk>/", views.delete_room, name="delete"),
    path("new_exit/<int:game_pk>/", views.create_exit, name="new_exit"),
    path("edit_exit/<int:game_pk>/<int:exit_pk>/", views.edit_exit, name="edit_exit"),
    path("delete_exit/<int:exit_pk>/", views.delete_exit, name="delete_exit"),
]

tbac/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

from . import views

urlpatterns = [
    path("", lambda r: HttpResponseRedirect(reverse("game:list"))),
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("game/", include("game.urls")),
    path("room/", include("room.urls")),
    path("item/", include("item.urls")),
]

game/models.py
from django.conf import settings
from django.db import models

from item.models import Item
from room.models import Exit

# Create your models here.


class GameManager(models.Manager):

    def playable(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        qs = self.filter(*args, **kwargs)
        if user:
            qs = qs.filter(models.Q(is_published=True) | models.Q(sessions__player=user))
        if "start_room" not in kwargs:
            qs = qs.filter(start_room__isnull=False)

        if "created_by" not in kwargs:
            qs = qs.filter(created_by__isnull=False)

        return qs


class EndStateManager(models.Manager):
    def base(self):
        return self.get_queryset().filter(session__isnull=True)

    def session(self, session_pk):
        return self.get_queryset().filter(session_id=session_pk)


class Game(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.CharField(max_length=1000)
    start_room = models.OneToOneField(
        "room.Room", related_name="starts_game", null=True, on_delete=models.SET_NULL
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="games",
        null=True,
        on_delete=models.SET_NULL,
    )
    is_published = models.BooleanField(default=False)

    objects = GameManager()

    def __str__(self):
        return self.name


class EndState(models.Model):
    """A Set of conditions that all must be true to reach an Ending in a Game
    EndState.is_success defines if the End State is a Win or Loss.
    """

    is_success = models.BooleanField(default=True)
    name = models.CharField(max_length=250)
    message = models.CharField(max_length=1000)
    game = models.ForeignKey(
        "Game", related_name="end_states", on_delete=models.CASCADE
    )
    session = models.ForeignKey(
        "Session",
        related_name="end_states",
        on_delete=models.CASCADE,
        null=True,
        default=None,
    )
    owned_items = models.ManyToManyField("item.Item", related_name="+")
    location = models.ForeignKey(
        "room.Room", related_name="+", null=True, blank=True, on_delete=models.SET_NULL
    )

    objects = EndStateManager()

    def end_state_met(self):
        print(self.owned_items.all())

        return all(self.owned_items.all().values_list("in_inventory", flat=True)) and (
            self.location is None or self.session.current_location == self.location
        )


class Session(models.Model):
    game = models.ForeignKey("Game", related_name="sessions", on_delete=models.CASCADE)
    current_location = models.ForeignKey(
        "room.Room",
        related_name="+",
        on_delete=models.CASCADE,
        limit_choices_to=models.Q(session__isnull=False),
        null=True,
    )
    player = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="sessions", on_delete=models.CASCADE
    )

    def get_inventory(self):
        return self.items.all().filter(in_inventory=True)

    def get_openable_containers(self):
        return self.get_inventory().filter(
            item_type=Item.ItemTypeChoices.CONTAINER, container_is_open=False
        )

    def get_exit_names_and_room_pks(self):
        """Used in a session to generate the list of directions a player can go."""
        exits = (
            Exit.objects.all()
            .filter(
                models.Q(room_1=self.current_location)
                | models.Q(room_2=self.current_location),
            )
            .values_list("room_1__pk", "room_2__pk", "one_to_two", "two_to_one")
        )

        return [
            (
                (one_to_two, room_2_pk)
                if room_1_pk == self.current_location.pk
                else (two_to_one, room_1_pk)
            )
            for room_1_pk, room_2_pk, one_to_two, two_to_one in exits
        ]

    def get_available_exits(self):
        """returns tuple pairs (exit direction label, room.pk)."""
        exits = (
            Exit.objects.filter(
                models.Q(room_1=self.current_location)
                | models.Q(room_2=self.current_location),
            )
            .select_related("room_1", "room_2")
            .prefetch_related("room_1__required_items", "room_2__required_items")
        )

        current_inventory = self.get_inventory()

        available_exit_data = []

        for location_exit in exits:
            moving_to = (
                location_exit.room_2
                if self.current_location == location_exit.room_1
                else location_exit.room_1
            )
            exit_label = (
                location_exit.one_to_two
                if self.current_location == location_exit.room_1
                else location_exit.two_to_one
            )

            if moving_to.required_items.exists() and any(
                not item.in_inventory for item in moving_to.required_items.all()
            ):
                continue

            available_exit_data.append((exit_label, moving_to.pk))

        return available_exit_data

game/forms.py
from django import forms

from room.models import Room
from item.models import Item


class GameForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"})
    )


class EndStateForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    message = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    location = forms.ModelChoiceField(
        queryset=Room.objects.none(),
        widget=forms.Select(attrs={"class": "form-select"}),
        required=False,
    )
    owned_items = forms.ModelMultipleChoiceField(
        widget=forms.SelectMultiple(attrs={"class": "form-select"}),
        required=False,
        queryset=Item.objects.none(),
    )
    is_success = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
        required=False,
        initial=True,
    )

    def __init__(self, *args, game_pk, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["location"].queryset = Room.objects.base().filter(game_id=game_pk)
        self.fields["owned_items"].queryset = Item.objects.base().filter(
            game_id=game_pk
        )


class ContinueGameForm(forms.Form):
    continue_adventure = forms.BooleanField(required=False)

game/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404

from . import forms, models
from room.models import Exit
from tbac import helpers

# Create your views here.


@login_required
def game_list(request):
    return render(
        request, "game/list.html", context={"games": models.Game.objects.playable(user=request.user)}
    )


def my_games(request):
    return render(
        request,
        "game/my_games.html",
        context={
            "games": models.Game.objects.filter(created_by=request.user),
            "links": [("+ new game", reverse("game:new"))],
        },
    )


def game_detail(request, game_pk, room_pk=None):
    game = get_object_or_404(models.Game, pk=game_pk)

    if room_pk is not None:
        room = game.rooms.get(pk=room_pk)
    else:
        room = game.start_room

    possible_exits = dict(
        exit_.get_exit_name_and_room_pk(room)
        for exit_ in Exit.objects.from_room(room=room)
    )

    return render(
        request,
        "game/detail.html",
        context={"game": game, "room": room, "exits": possible_exits},
    )


@login_required
def create_game(request):
    form = forms.GameForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        game = models.Game.objects.create(
            name=form.cleaned_data["name"],
            description=form.cleaned_data["description"],
            created_by=request.user,
        )
        return HttpResponseRedirect(
            reverse("game:dashboard", kwargs={"game_pk": game.pk})
        )

    return render(request, "game/game_form.html", context={"form": form})


def edit_game(request, game_pk):
    game = get_object_or_404(models.Game, pk=game_pk)

    form = forms.GameForm(
        request.POST or None,
        initial={
            "name": game.name,
            "description": game.description,
        },
    )
    if request.method == "POST" and form.is_valid():
        game.name = form.cleaned_data["name"]
        game.description = form.cleaned_data["description"]
        game.save()
        return HttpResponseRedirect(
            reverse("game:dashboard", kwargs={"game_pk": game.pk})
        )

    return render(request, "game/game_form.html", context={"form": form})


@login_required
def game_dashboard(request, game_pk):
    game = get_object_or_404(
        models.Game.objects.filter(created_by=request.user)
        .prefetch_related("rooms", "items")
        .select_related("start_room"),
        pk=game_pk,
    )

    all_exits = (
        Exit.objects.base()
        .filter(Q(room_1__game=game) | Q(room_2__game=game))
        .select_related("room_1", "room_2")
    )

    publish_link = (
        "publish", reverse("game:publish", kwargs={"game_pk": game_pk})
    ) if not game.is_published else (
        "unpublish", reverse("game:unpublish", kwargs={"game_pk": game_pk})
    )

    return render(
        request,
        "game/dashboard.html",
        context={
            "game": game,
            "exits": all_exits,
            "links": [
                ("back", reverse("game:my_games")),
                ("edit", reverse("game:edit", kwargs={"game_pk": game_pk})),
                publish_link,
            ],
        },
    )


@login_required
def publish_game(request, game_pk):
    game = get_object_or_404(models.Game, pk=game_pk, created_by=request.user)

    game.is_published = True
    game.save()
    return helpers.custom_redirect("game:dashboard", {"game_pk": game_pk})


@login_required
def unpublish_game(request, game_pk):
    game = get_object_or_404(models.Game, pk=game_pk, created_by=request.user)

    game.is_published = False
    game.save()
    return helpers.custom_redirect("game:dashboard", {"game_pk": game_pk})

def new_end_state(request, game_pk):
    game = get_object_or_404(models.Game, pk=game_pk)
    form = forms.EndStateForm(
        request.POST or None,
        game_pk=game.pk,
    )

    if request.method == "POST" and form.is_valid():
        end_state = models.EndState.objects.create(
            game=game,
            name=form.cleaned_data["name"],
            message=form.cleaned_data["message"],
            is_success=form.cleaned_data["is_success"],
            location=form.cleaned_data["location"],
        )
        end_state.owned_items.set(form.cleaned_data["owned_items"])

        return HttpResponseRedirect(
            reverse("game:dashboard", kwargs={"game_pk": game.pk})
        )

    return render(
        request,
        "game/end_state_form.html",
        context={
            "game": game,
            "form": form,
            "editing": False,
        },
    )


def edit_end_state(request, end_state_pk):
    end_state = get_object_or_404(
        models.EndState.objects.select_related("game", "location").prefetch_related(
            "owned_items"
        ),
        pk=end_state_pk,
    )
    form = forms.EndStateForm(
        request.POST or None,
        game_pk=end_state.game.pk,
        initial={
            "name": end_state.name,
            "message": end_state.message,
            "is_success": end_state.is_success,
            "location": (
                end_state.location.pk if end_state.location is not None else None
            ),
            "owned_items": end_state.owned_items.values_list("pk", flat=True),
        },
    )

    if request.method == "POST" and form.is_valid():
        end_state.name = form.cleaned_data["name"]
        end_state.message = form.cleaned_data["message"]
        end_state.is_success = form.cleaned_data["is_success"]
        end_state.location = form.cleaned_data["location"]
        end_state.save()
        end_state.owned_items.set(form.cleaned_data["owned_items"])

        return HttpResponseRedirect(
            reverse("game:dashboard", kwargs={"game_pk": end_state.game.pk})
        )

    return render(
        request,
        "game/end_state_form.html",
        context={
            "game": end_state.game,
            "form": form,
            "editing": True,
        },
    )


def delete_end_state(request, end_state_pk):
    end_state = get_object_or_404(
        models.EndState.select_related("game"), pk=end_state_pk
    )
    game_pk = end_state.game.pk
    end_state.delete()

    return HttpResponseRedirect(
        reverse("game:dashboard", kwargs={"game_pk": end_state.game.pk})
    )

game/templates/game/continue.html
{% extends "base.html" %}


{% block page_title %}Continue?{% endblock %}

{% block content %}

<div class="container w-50 text-center">
  <p>
    You already have progress in this Adventure, would you like to continue from where you left off or restart?
    (If you choose to restart you will never be able to access your current progress again.)
  </p>
  <div class="container w-50">
    <form method="POST">
      {% csrf_token %}
      {{ form.errors }}
      <table class="table table-borderless">
        <tr>
          <th class="text-center"><button type="submit" class="btn btn-primary" name="continue_adventure" value=true>Continue</button></th>
        </tr>
        <tr>
          <th class="text-center"><button type="submit" class="btn btn-danger" name="continue_adventure" value=false>Restart</button></th>
        </tr>
      </table>
    </form>
  </div>
</div>

{% endblock %}

game/templates/game/dashboard.html
{% extends "base.html" %}

{% block page_title %}{{ game.name }}{% endblock %}

{% block content %}

<div class="container">
  <div class="row row-cols-3 row-cols-md-3 g-4">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Rooms</h5>
          <a href="{% url 'room:new' game.pk %}" class="card-link">+ New Room</a>
        </div>
        <ul class="list-group list-group-flush">
            {% for room in game.rooms.base %}
              <li class="list-group-item">
                <table class="table table-borderless table-sm m-0">
                <tr>
                  <td class="w-100">{{ room.name }}</td>
                  <td
                    data-bs-toggle="popover"
                    data-bs-trigger="hover focus"
                    data-bs-placement="top"
                    data-bs-content="{% if room.pk == game.start_room.pk %}this is the starting room{% else %}set the starting room{% endif %}"
                  >
                    {% if room.pk == game.start_room.pk %}
                      <svg width="1.25em" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
                      </svg>
                    {% else %}
                      <a href="{% url 'room:set_starting' room.pk %}">
                        <svg width="1.25em" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
                        </svg>

                      </a>
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'room:edit' room.pk %}">
                      {% include "icons/edit.html" %}
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'room:delete' room.pk %}">
                      {% include "icons/delete.html" %}
                    </a>
                  </td>
                </tr>
                </table>
              </li>
            {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Exits</h5>
          <a href="{% url 'room:new_exit' game.pk %}" class="card-link">+ New Exit</a>
        </div>
        <ul class="list-group list-group-flush">
          {% for exit in exits %}
            <li class="list-group-item">
              <table class="table table-borderless table-sm m-0">
                <tr>
                  <td class="w-100">
                    {{ exit.room_1.name }} &lt;-&gt; {{ exit.room_2.name }}
                  </td>
                  <td>
                    <a href="{% url 'room:edit_exit' game_pk=game.pk exit_pk=exit.pk %}">
                      {% include "icons/edit.html" %}
                    </a>
                  </td>
                  <td><a href="{% url 'room:delete_exit' exit.pk %}">
                      {% include "icons/delete.html" %}
                  </a></td>
                </tr>
              </table>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Items</h5>
          <a href="{% url 'item:new' game.pk %}" class="card-link">+ New Item</a>
        </div>
        <ul class="list-group list-group-flush">
          {% for item in game.items.base %}
            <li class="list-group-item">
              <table class="table table-borderless table-sm m-0">
                <tr>
                  <td
                    class="w-100"
                    data-bs-toggle="popover"
                    data-bs-trigger="hover focus"
                    data-bs-placement="left"
                    data-bs-content="{% if item.is_starting_item %}Starting Item{% elif item.room %}Item is found in {{ item.room.name }}{% else %}Item is hidden in {{ item.contained_within.name }}{% endif %}"
                  >
                    {{ item.name }}
                  </td>
                  <td>
                    <a href="{% url 'item:edit' item.pk %}">
                      {% include "icons/edit.html" %}
                    </a>
                  </td>
                  <td><a href="{% url 'item:delete' item.pk %}">
                      {% include "icons/delete.html" %}
                  </a></td>
                </tr>
              </table>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">End States</h5>
          <a href="{% url 'game:new_end_state' game.pk %}" class="card-link">+ New End State</a>
        </div>
        <ul class="list-group list-group-flush">
          {% for state in game.end_states.base %}
            <li class="list-group-item">
              <table class="table table-borderless table-sm m-0">
                <tr>
                  <td>{{ state.name }}</td>
                  <td>
                    <a href="{% url 'game:edit_end_state' state.pk %}">
                      {% include "icons/edit.html" %}
                    </a>
                  </td>
                  <td><a href="{% url 'game:delete_end_state' state.pk %}">
                      {% include "icons/delete.html" %}
                  </a></td>
                </tr>
              </table>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

</div>

{% endblock %}

game/templates/game/detail.html
{% extends "base.html" %}

{% block page_title %}{{ game.name }}{% endblock %}


{% block content %}

<div class="container">
  <p>{{ game.description }}</p>
</div>

<div class="contaner border p-2">
  <p>{{ room.description }}</p>
  <p>You can see: {{ room.items.all | join:", " }}</p>
  <p>You Can:</p>
  <p>
    {% for exit, pk in exits.items %}
      <a href="{% url 'game:detail' game_pk=game.pk room_pk=pk %}">
        {{ exit }}<br />
      </a>
    {% endfor %}
    {% for item in room.items.all %}
      Take {{ item.name }}<br />
    {% endfor %}
  </p>
</div>

{% endblock %}

game/templates/game/end.html
{% extends "base.html" %}

{% block page_title %}{{ game.name }}{% endblock %}


{% block content %}

<div class="container">
  <p>{{ game.description }}</p>
</div>

<div class="contaner border p-2">
  <h3>{{ end_state.name }}</h3>
  <p>{{ end_state.message }}</p>
</div>

{% endblock %}

game/templates/game/end_state_form.html
{% extends "base.html" %}


{% block page_title %}
  {% if editing %}
    End State Editor
  {% else %}
    {{ game.name }}
  {% endif %}
{% endblock %}

{% block content %}

<div class="container">
  <form method="POST">
    {% csrf_token %}
    <table class="table">
      <tr>
        <th>End State Name</th>
        <td>{{ form.name }} {{ form.name.errors.as_text }}</td>
      </tr>
      <tr>
        <th>Achievement Message</th>
        <td>{{ form.message }} {{ form.message.errors.as_text }}</td>
      </tr>
      <tr>
        <th>Is a Win State?</th>
        <td>{{ form.is_success }} {{ form.is_success.errors.as_text }}</td>
      </tr>
      <tr>
        <th>Required Location (Optional)</th>
        <td>{{ form.location }} {{ form.location.errors.as_text }}</td>
      </tr>
      <tr>
        <th>Required Items in Inventory</th>
        <td>{{ form.owned_items }} {{ form.owned_items.errors.as_text }}</td>
      </tr>
      <tr>
        <th colspan=2 class="text-center">
          <button type="submit" class="btn btn-primary">
            {% if editing %}Save{% else %}Create{% endif %}
          </button>
        </th>
      </tr>
    </table>
  </form>
</div>

{% endblock %}

game/templates/game/game_form.html
{% extends "base.html" %}


{% block page_title %}New Game{% endblock %}

{% block content %}

<div class="container">
  <form method="POST">
    {% csrf_token %}
    <table class="table">
      <tr>
        <th>Name</th><td>{{ form.name }} {{ form.name.errors.as_text }}</td>
      </tr>
      <tr>
        <th>Description</th><td>{{ form.description }} {{ form.description.errors.as_text }}</td>
      </tr>
      <tr><th colspan=2 class="text-center"><button type="submit" class="btn btn-primary">Create</button></th></tr>
    </table>
  </form>
</div>

{% endblock %}

game/templates/game/list.html
{% extends "base.html" %}


{% block page_title %}Games{% endblock %}


{% block content %}

<div class="container text-center">
  <table class="table">
    <thead><tr><th>Text-Based Adventure Games</th></tr></thead>
    <tbody>
      {% for game in games %}
        <tr>
          <td><a href="{% url 'game:start_session' game.pk %}">{{ game.name }}</a></td>
        </tr>
      {% empty %}
        <tr><th>No Games Found</th></tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

game/templates/game/my_games.html
{% extends "base.html" %}


{% block page_title %}My Games{% endblock %}


{% block content %}

<div class="container text-center">
  <table class="table">
    <thead><tr><th>Text-Based Adventure Games</th></tr></thead>
    <tbody>
      {% for game in games %}
        <tr>
          <td><a href="{% url 'game:dashboard' game.pk %}">{{ game.name }}</a></td>
        </tr>
      {% empty %}
        <tr><th>No Games Found</th></tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

game/templates/game/play.html
{% extends "base.html" %}

{% block page_title %}{{ game.name }}{% endblock %}


{% block content %}

<div class="container">
  <p>{{ game.description }}</p>
</div>

<div class="contaner border p-2">
  <p>{{ location.description }}</p>
  {% if items.exists %}
    <p>You can see: {{ items | join:", " }}</p>
  {% endif %}
  {% if inventory.exists %}
    <p>You have at your disposal: {{ inventory | join:", " }}</p>
  {% endif %}
  <p>You can:</p>
  <p>
    {% for exit, pk in exits %}
      <a href="{% url 'game:move' session_pk=session.pk room_pk=pk %}">
        {{ exit }}<br />
      </a>
    {% endfor %}
    {% for item in items %}
      <a href="{% url 'game:take' session_pk=session.pk item_pk=item.pk %}">
        Take {{ item.name }}<br />
      </a>
    {% endfor %}
    {% for item in containers %}
      <a href="{% url 'game:open' session_pk=session.pk item_pk=item.pk %}">
        Open {{ item.name }}</br />
      </a>
    {% endfor %}
  </p>
</div>

{% endblock %}